### PR TITLE
allow nested @-operators in TPTP parser

### PR DESCRIPTION
**Pull request by benti**

### CODE REVIEW

**Comment by benti** [comment]
Yes, but then `f @ a @ b` would be parsed into `PT.app(PT.app f [a]) [b]`, which leads to the nested `STerm.App`s that I tried to avoid in the earlier pull request.

**Comment by c-cube** [comment]
Ah indeed, the smart constructor `STerm.app` was wrong. Fixed.

**Comment by benti** [comment]
If `STerm.app` was wrong, we now fixed the wrong part. I am confused...

**Comment by benti** [comment]
OK, now I saw your commit  https://github.com/c-cube/zipperposition/commit/ac39afc866e49fa110614b5716fc9f9bc69e08f6 Perfect!

**Pull request merged**
